app:
    resource: "@AnaxagoCoreBundle/Controller/"
    type: annotation
    
anaxago_core:
    resource: "@AnaxagoCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AnaxagoCoreBundle:Security:login }

logout:
    path: /logout

anaxago_core_registration:
    path: /register
    defaults: { _controller: AnaxagoCoreBundle:Security:registration }

#projects_list:
  #  path: /projects
   # defaults: { _controller: AnaxagoCoreBundle:Project:getProjects }